### ISSUE TITLE
예전 작업 공유

### ISSUE THREAD

**Issue by sn0wle0pard** [kcm4482/unist_bb_downloader#1]
private repo이긴 한데 (학교랑 문제있을까봐 bb파일 가져오는 url 감추기용) https://github.com/sn0wle0pard/BBdownloder 이전에 만든 bb.hexa.pro 코드 드릴까요? 플라스크로 만들었어요

**Comment by kcm4482** [comment]
오 진짜? 주면 땡큐지ㅎㅎ
BB 넘 이상하게 꼬아놔서 일일이 푸는게 쉽지않다..ㅋㅋ

**Comment by sn0wle0pard** [comment]
권한 드렸습니다
